### ISSUE TITLE
returned value codes

### ISSUE THREAD

**Issue by shimada-development** [skynav/ttpe#9]
Currently an "int" is being returned as status code. A more elaborate way to specify return code will help us identify errors.

I believe, it returns 0 for success and non-zero values for errors. Could we introduce error codes to get more specific error states/success?

**Comment by skynavga** [comment]
The following two methods are already available on the TTPE Presenter:

`public int getResultCode(String uri)`
`public int getResultFlags(String uri)`

In order to expose more result state, I have also added the following method to TimedTextTransformer, inherited by Presenter:

`public TimedTextVerifier.Results getResults(String uri)`

The _uri_ argument to these methods should match one of the URI strings passed as a command line option to TTPE, which specifies the source of the input TTML resource.
